/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.modules.menu_config.view;

/**
 *
 * @author nacho
 */
public class app_view extends javax.swing.JFrame {

    /**
     * Creates new form app_view
     */
    public static config_view configview;

    public app_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminsButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        usregButton = new javax.swing.JButton();
        confButton = new javax.swing.JButton();
        labelMenu = new javax.swing.JLabel();
        conflabel = new javax.swing.JLabel();
        adminlabel = new javax.swing.JLabel();
        clientslabel = new javax.swing.JLabel();
        userslabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/modules/menu_config/view/img/user_admin.png"))); // NOI18N
        adminsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsButtonActionPerformed(evt);
            }
        });

        clientsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/modules/menu_config/view/img/user_man.png"))); // NOI18N

        usregButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/modules/menu_config/view/img/users.png"))); // NOI18N

        confButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/modules/menu_config/view/img/configuration.png"))); // NOI18N
        confButton.setToolTipText("");
        confButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confButtonActionPerformed(evt);
            }
        });

        labelMenu.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        labelMenu.setText("Choose an option:");

        conflabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        conflabel.setText("Configuration");

        adminlabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        adminlabel.setText("Admins");

        clientslabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        clientslabel.setText("Clients");

        userslabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        userslabel.setText("Registered users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMenu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminsButton)
                            .addComponent(adminlabel)
                            .addComponent(usregButton)
                            .addComponent(userslabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientslabel)
                            .addComponent(clientsButton)
                            .addComponent(conflabel)
                            .addComponent(confButton))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientslabel)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conflabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usregButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userslabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsButtonActionPerformed

    }//GEN-LAST:event_adminsButtonActionPerformed

    private void confButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confButtonActionPerformed
        
    }//GEN-LAST:event_confButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel adminlabel;
    public static javax.swing.JButton adminsButton;
    public static javax.swing.JButton clientsButton;
    public static javax.swing.JLabel clientslabel;
    public static javax.swing.JButton confButton;
    public static javax.swing.JLabel conflabel;
    public static javax.swing.JLabel labelMenu;
    public static javax.swing.JLabel userslabel;
    public static javax.swing.JButton usregButton;
    // End of variables declaration//GEN-END:variables
}
