/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.modules.login.view;

/**
 *
 * @author nacho
 */
public class login_view extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        typecombo = new javax.swing.JComboBox<>();
        passwordLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        wrongpass = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setText("Welcome to the app");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(usernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 135, -1));

        typecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Registered User", "Admin" }));
        getContentPane().add(typecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 135, -1));
        getContentPane().add(passwordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 135, -1));

        jLabel4.setText("Type of user");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        loginbutton.setText("Log In");
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 83, -1));

        wrongpass.setForeground(new java.awt.Color(255, 0, 0));
        wrongpass.setText("Wrong user or password");
        getContentPane().add(wrongpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/modules/login/view/img/locked.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JButton loginbutton;
    public static javax.swing.JTextField passwordLogin;
    public static javax.swing.JComboBox<String> typecombo;
    public static javax.swing.JTextField usernameLogin;
    public static javax.swing.JLabel wrongpass;
    // End of variables declaration//GEN-END:variables
}
