/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.modules.admin.view;

/**
 *
 * @author nacho
 */
public class admin_view extends javax.swing.JFrame {

    /**
     * Creates new form admin_view
     */
    public admin_view() {
        initComponents();
    }

    public static int Admintochange;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAButton = new javax.swing.JButton();
        changeDataAButton = new javax.swing.JButton();
        deleteDataAButton = new javax.swing.JButton();
        findAButton = new javax.swing.JButton();
        sortbyAButton = new javax.swing.JButton();
        exportAButton = new javax.swing.JButton();
        importAButton = new javax.swing.JButton();
        tabbedtable = new javax.swing.JTabbedPane();
        panelviews = new javax.swing.JPanel();
        list = new javax.swing.JScrollPane();
        adminstable = new javax.swing.JTable();
        beginning = new javax.swing.JButton();
        backwards = new javax.swing.JButton();
        forward = new javax.swing.JButton();
        end = new javax.swing.JButton();
        pagefield = new javax.swing.JTextField();
        combopage = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        numtab1 = new javax.swing.JButton();
        numtab2 = new javax.swing.JButton();
        numtab3 = new javax.swing.JButton();
        numtab4 = new javax.swing.JButton();
        numtab5 = new javax.swing.JButton();
        numtab6 = new javax.swing.JButton();
        numtab7 = new javax.swing.JButton();
        formviewp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dniform = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameform = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        surnameform = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        phoneform = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailform = new javax.swing.JTextField();
        userform = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stateform = new javax.swing.JTextField();
        birthdayform = new javax.swing.JTextField();
        hiringdateform = new javax.swing.JTextField();
        salaryform = new javax.swing.JTextField();
        activityform = new javax.swing.JTextField();
        avatarform = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ageform = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        admincreated = new javax.swing.JLabel();
        backA = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        autocompletefield = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        filemenu = new javax.swing.JMenu();
        importmenu = new javax.swing.JMenuItem();
        exportmenu = new javax.swing.JMenuItem();
        sortmenu = new javax.swing.JMenu();
        viewsmenu = new javax.swing.JMenu();
        listmenu = new javax.swing.JMenuItem();
        formmenu = new javax.swing.JMenuItem();
        kanbanmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createAButton.setText("Create");
        createAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAButtonActionPerformed(evt);
            }
        });

        changeDataAButton.setText("Change Data");
        changeDataAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDataAButtonActionPerformed(evt);
            }
        });

        deleteDataAButton.setText("Delete");
        deleteDataAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataAButtonActionPerformed(evt);
            }
        });

        findAButton.setText("Find");
        findAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAButtonActionPerformed(evt);
            }
        });

        sortbyAButton.setText("Sort By");
        sortbyAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyAButtonActionPerformed(evt);
            }
        });

        exportAButton.setText("Export");
        exportAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportAButtonActionPerformed(evt);
            }
        });

        importAButton.setText("Import");
        importAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importAButtonActionPerformed(evt);
            }
        });

        panelviews.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        adminstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "DNI", "Name", "Surname", "Phone", "Email", "User", "Status", "Birthday", "Age", "Hiring Date", "Salary", "Activity"
            }
        ));
        adminstable.getTableHeader().setReorderingAllowed(false);
        adminstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminstableMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminstableMouseClicked(evt);
            }
        });
        list.setViewportView(adminstable);
        adminstable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        beginning.setText("|<");
        beginning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginningActionPerformed(evt);
            }
        });

        backwards.setText("<");
        backwards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardsActionPerformed(evt);
            }
        });

        forward.setText(">");
        forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardActionPerformed(evt);
            }
        });

        end.setText(">|");
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });

        pagefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pagefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagefieldActionPerformed(evt);
            }
        });

        combopage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show 10 Admins", "Show 20 Admins", "Show 50 Admins", "Show 100 Admins" }));
        combopage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopageActionPerformed(evt);
            }
        });

        jPanel2.setBorder(null);

        numtab1.setText("1");
        numtab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab1ActionPerformed(evt);
            }
        });

        numtab2.setText("2");
        numtab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab2ActionPerformed(evt);
            }
        });

        numtab3.setText("3");
        numtab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab3ActionPerformed(evt);
            }
        });

        numtab4.setText("4");
        numtab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab4ActionPerformed(evt);
            }
        });

        numtab5.setText("5");
        numtab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab5ActionPerformed(evt);
            }
        });

        numtab6.setText("6");
        numtab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab6ActionPerformed(evt);
            }
        });

        numtab7.setText("7");
        numtab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtab7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numtab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numtab7)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numtab1)
                    .addComponent(numtab2)
                    .addComponent(numtab3)
                    .addComponent(numtab4)
                    .addComponent(numtab5)
                    .addComponent(numtab6)
                    .addComponent(numtab7))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panelviewsLayout = new javax.swing.GroupLayout(panelviews);
        panelviews.setLayout(panelviewsLayout);
        panelviewsLayout.setHorizontalGroup(
            panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewsLayout.createSequentialGroup()
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelviewsLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backwards))
                    .addComponent(beginning))
                .addGap(29, 29, 29)
                .addComponent(pagefield, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelviewsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(forward))
                    .addGroup(panelviewsLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(end)))
                .addGap(118, 118, 118)
                .addComponent(combopage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelviewsLayout.setVerticalGroup(
            panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelviewsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backwards)
                    .addComponent(beginning))
                .addGap(3, 3, 3))
            .addGroup(panelviewsLayout.createSequentialGroup()
                .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelviewsLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(forward)
                                .addComponent(pagefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(end)
                                .addComponent(combopage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
        );

        tabbedtable.addTab("List", panelviews);

        jLabel2.setText("DNI:");

        dniform.setEditable(false);

        jLabel4.setText("Name:");

        nameform.setEditable(false);

        jLabel6.setText("Surname:");

        surnameform.setEditable(false);

        jLabel1.setText("Phone:");

        phoneform.setEditable(false);

        jLabel3.setText("Email:");

        jLabel5.setText("User:");

        emailform.setEditable(false);

        userform.setEditable(false);

        jLabel7.setText("Status:");

        jLabel8.setText("Birthday:");

        jLabel9.setText("Hiring date:");

        jLabel10.setText("Salary:");

        jLabel11.setText("Activity:");

        stateform.setEditable(false);

        birthdayform.setEditable(false);

        hiringdateform.setEditable(false);

        salaryform.setEditable(false);

        activityform.setEditable(false);

        avatarform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Age:");

        ageform.setEditable(false);

        javax.swing.GroupLayout formviewpLayout = new javax.swing.GroupLayout(formviewp);
        formviewp.setLayout(formviewpLayout);
        formviewpLayout.setHorizontalGroup(
            formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formviewpLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(formviewpLayout.createSequentialGroup()
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameform)
                            .addComponent(dniform)
                            .addComponent(surnameform)
                            .addComponent(phoneform, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formviewpLayout.createSequentialGroup()
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdayform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formviewpLayout.createSequentialGroup()
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailform, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userform, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiringdateform)
                    .addComponent(salaryform)
                    .addComponent(activityform)
                    .addComponent(ageform, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(89, 89, 89)
                .addComponent(avatarform, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        formviewpLayout.setVerticalGroup(
            formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formviewpLayout.createSequentialGroup()
                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formviewpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formviewpLayout.createSequentialGroup()
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(dniform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(nameform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(surnameform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(phoneform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(formviewpLayout.createSequentialGroup()
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12)
                                    .addComponent(ageform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formviewpLayout.createSequentialGroup()
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(userform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stateform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(birthdayform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(formviewpLayout.createSequentialGroup()
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(hiringdateform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(salaryform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(formviewpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(activityform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(formviewpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(avatarform, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tabbedtable.addTab("Form", formviewp);

        jLabel13.setText("Coming soon...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(1038, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        tabbedtable.addTab("Kanban", jPanel3);

        admincreated.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        admincreated.setForeground(new java.awt.Color(18, 107, 1));

        backA.setText("Volver");

        jLabel14.setText("Search:");

        filemenu.setText("File");

        importmenu.setText("Import");
        importmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importmenuActionPerformed(evt);
            }
        });
        filemenu.add(importmenu);

        exportmenu.setText("Export");
        exportmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportmenuActionPerformed(evt);
            }
        });
        filemenu.add(exportmenu);

        jMenuBar1.add(filemenu);

        sortmenu.setText("Sort");
        jMenuBar1.add(sortmenu);

        viewsmenu.setText("Views");

        listmenu.setText("List");
        listmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listmenuActionPerformed(evt);
            }
        });
        viewsmenu.add(listmenu);

        formmenu.setText("Form");
        formmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formmenuActionPerformed(evt);
            }
        });
        viewsmenu.add(formmenu);

        kanbanmenu.setText("Kanban");
        viewsmenu.add(kanbanmenu);

        jMenuBar1.add(viewsmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedtable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(findAButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(createAButton, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sortbyAButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exportAButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(changeDataAButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteDataAButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(admincreated, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(autocompletefield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(313, 313, 313)))
                        .addGap(237, 237, 237)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(importAButton)
                            .addComponent(backA))
                        .addGap(213, 213, 213)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedtable, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(admincreated, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autocompletefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(findAButton)
                        .addComponent(sortbyAButton)
                        .addComponent(exportAButton)
                        .addComponent(importAButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createAButton)
                            .addComponent(changeDataAButton)
                            .addComponent(deleteDataAButton)
                            .addComponent(backA))
                        .addGap(60, 60, 60)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAButtonActionPerformed
        
    }//GEN-LAST:event_createAButtonActionPerformed

    private void changeDataAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDataAButtonActionPerformed
        
    }//GEN-LAST:event_changeDataAButtonActionPerformed

    private void deleteDataAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataAButtonActionPerformed
        
    }//GEN-LAST:event_deleteDataAButtonActionPerformed

    private void findAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAButtonActionPerformed
        
    }//GEN-LAST:event_findAButtonActionPerformed

    private void exportAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportAButtonActionPerformed
        
    }//GEN-LAST:event_exportAButtonActionPerformed

    private void importAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importAButtonActionPerformed
        
    }//GEN-LAST:event_importAButtonActionPerformed

    private void sortbyAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyAButtonActionPerformed
        
    }//GEN-LAST:event_sortbyAButtonActionPerformed

    private void exportmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportmenuActionPerformed
        
    }//GEN-LAST:event_exportmenuActionPerformed

    private void importmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importmenuActionPerformed

    }//GEN-LAST:event_importmenuActionPerformed

    private void listmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listmenuActionPerformed
        
    }//GEN-LAST:event_listmenuActionPerformed

    private void adminstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminstableMouseClicked

    }//GEN-LAST:event_adminstableMouseClicked

    private void adminstableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminstableMousePressed

    }//GEN-LAST:event_adminstableMousePressed

    private void forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardActionPerformed
        
    }//GEN-LAST:event_forwardActionPerformed

    private void backwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardsActionPerformed
        
    }//GEN-LAST:event_backwardsActionPerformed

    private void combopageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopageActionPerformed
        
    }//GEN-LAST:event_combopageActionPerformed

    private void beginningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginningActionPerformed
        
    }//GEN-LAST:event_beginningActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        
    }//GEN-LAST:event_endActionPerformed

    private void pagefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagefieldActionPerformed
        
    }//GEN-LAST:event_pagefieldActionPerformed

    private void formmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formmenuActionPerformed
        
    }//GEN-LAST:event_formmenuActionPerformed

    private void numtab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab1ActionPerformed
        
    }//GEN-LAST:event_numtab1ActionPerformed

    private void numtab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab2ActionPerformed
        
    }//GEN-LAST:event_numtab2ActionPerformed

    private void numtab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab3ActionPerformed
        
    }//GEN-LAST:event_numtab3ActionPerformed

    private void numtab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab4ActionPerformed
        
    }//GEN-LAST:event_numtab4ActionPerformed

    private void numtab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab5ActionPerformed
        
    }//GEN-LAST:event_numtab5ActionPerformed

    private void numtab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab6ActionPerformed
        
    }//GEN-LAST:event_numtab6ActionPerformed

    private void numtab7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtab7ActionPerformed
        
    }//GEN-LAST:event_numtab7ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField activityform;
    public static javax.swing.JLabel admincreated;
    public static javax.swing.JTable adminstable;
    public static javax.swing.JTextField ageform;
    public static javax.swing.JTextField autocompletefield;
    public static javax.swing.JLabel avatarform;
    public static javax.swing.JButton backA;
    public static javax.swing.JButton backwards;
    public static javax.swing.JButton beginning;
    public static javax.swing.JTextField birthdayform;
    public static javax.swing.JButton changeDataAButton;
    public static javax.swing.JComboBox<String> combopage;
    public static javax.swing.JButton createAButton;
    public static javax.swing.JButton deleteDataAButton;
    public static javax.swing.JTextField dniform;
    public static javax.swing.JTextField emailform;
    public static javax.swing.JButton end;
    public static javax.swing.JButton exportAButton;
    public static javax.swing.JMenuItem exportmenu;
    public static javax.swing.JMenu filemenu;
    public static javax.swing.JButton findAButton;
    public static javax.swing.JMenuItem formmenu;
    public static javax.swing.JPanel formviewp;
    public static javax.swing.JButton forward;
    public static javax.swing.JTextField hiringdateform;
    public static javax.swing.JButton importAButton;
    public static javax.swing.JMenuItem importmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JMenuItem kanbanmenu;
    public static javax.swing.JScrollPane list;
    public static javax.swing.JMenuItem listmenu;
    public static javax.swing.JTextField nameform;
    public static javax.swing.JButton numtab1;
    public static javax.swing.JButton numtab2;
    public static javax.swing.JButton numtab3;
    public static javax.swing.JButton numtab4;
    public static javax.swing.JButton numtab5;
    public static javax.swing.JButton numtab6;
    public static javax.swing.JButton numtab7;
    public static javax.swing.JTextField pagefield;
    public static javax.swing.JPanel panelviews;
    public static javax.swing.JTextField phoneform;
    public static javax.swing.JTextField salaryform;
    public static javax.swing.JButton sortbyAButton;
    public static javax.swing.JMenu sortmenu;
    public static javax.swing.JTextField stateform;
    public static javax.swing.JTextField surnameform;
    public static javax.swing.JTabbedPane tabbedtable;
    public static javax.swing.JTextField userform;
    public static javax.swing.JMenu viewsmenu;
    // End of variables declaration//GEN-END:variables
}
